# render.yaml
services:
  - type: web
    name: social-media-analytics-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api:app
    envVars:
      - key: ASTRA_DB_BUNDLE_PATH
        sync: false
      - key: ASTRA_DB_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false